#!/bin/bash

# Interactive Project Setup Script
# Configures project name, registry, and namespace for the template
#
# Usage: ./scripts/setup-project.sh
#
# This script:
# 1. Prompts for project configuration values
# 2. Writes project.env file
# 3. Optionally updates Kubernetes manifests

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

echo ""
echo -e "${BLUE}=== Project Configuration Setup ===${NC}"
echo ""

# Check if project.env already exists
if [ -f "$PROJECT_ROOT/project.env" ]; then
    source "$PROJECT_ROOT/project.env"
    echo "Existing configuration found:"
    echo "  PROJECT_NAME: $PROJECT_NAME"
    echo "  REGISTRY: $REGISTRY"
    echo "  NAMESPACE_PREFIX: ${NAMESPACE_PREFIX:-$PROJECT_NAME}"
    echo ""
    read -p "Do you want to reconfigure? (y/N) " RECONFIGURE
    if [[ ! "$RECONFIGURE" =~ ^[Yy] ]]; then
        log_info "Keeping existing configuration."
        exit 0
    fi
    echo ""
fi

# Interactive prompts with defaults
echo "Enter your project configuration:"
echo ""

# Project name
DEFAULT_PROJECT_NAME="${PROJECT_NAME:-my-app}"
read -p "Project name (lowercase, hyphens ok) [$DEFAULT_PROJECT_NAME]: " INPUT_PROJECT_NAME
PROJECT_NAME="${INPUT_PROJECT_NAME:-$DEFAULT_PROJECT_NAME}"

# Validate project name
if [[ ! "$PROJECT_NAME" =~ ^[a-z][a-z0-9-]*[a-z0-9]$ ]] && [[ ! "$PROJECT_NAME" =~ ^[a-z]$ ]]; then
    log_error "Project name must be lowercase alphanumeric with optional hyphens"
    log_error "  - Must start with a letter"
    log_error "  - Can contain lowercase letters, numbers, and hyphens"
    log_error "  - Must end with a letter or number"
    exit 1
fi

# Registry
DEFAULT_REGISTRY="${REGISTRY:-quay.io/myorg}"
read -p "Container registry [$DEFAULT_REGISTRY]: " INPUT_REGISTRY
REGISTRY="${INPUT_REGISTRY:-$DEFAULT_REGISTRY}"

# Namespace prefix
echo ""
echo "Namespace prefix is used for Kubernetes namespaces:"
echo "  Namespaces will be: {prefix}-dev and {prefix}-prod"
echo "  Leave empty to use project name as prefix"
DEFAULT_NAMESPACE="${NAMESPACE_PREFIX:-}"
read -p "Namespace prefix (leave empty for '$PROJECT_NAME') [$DEFAULT_NAMESPACE]: " INPUT_NAMESPACE
NAMESPACE_PREFIX="${INPUT_NAMESPACE:-$DEFAULT_NAMESPACE}"

# Write project.env
cat > "$PROJECT_ROOT/project.env" << EOF
# Project Identity Configuration
# Generated by setup-project.sh on $(date)

# Project name - used for container image naming
PROJECT_NAME=$PROJECT_NAME

# Container registry - where images will be pushed
REGISTRY=$REGISTRY

# Namespace prefix for Kubernetes deployments
NAMESPACE_PREFIX=$NAMESPACE_PREFIX
EOF

echo ""
log_info "Configuration saved to project.env"
echo ""
echo "  PROJECT_NAME: $PROJECT_NAME"
echo "  REGISTRY: $REGISTRY"
echo "  NAMESPACE_PREFIX: ${NAMESPACE_PREFIX:-$PROJECT_NAME}"
echo ""
echo "  Backend image: $REGISTRY/$PROJECT_NAME-backend"
echo "  Frontend image: $REGISTRY/$PROJECT_NAME-frontend"
echo "  Dev namespace: ${NAMESPACE_PREFIX:-$PROJECT_NAME}-dev"
echo "  Prod namespace: ${NAMESPACE_PREFIX:-$PROJECT_NAME}-prod"
echo ""

# Ask about updating K8s manifests
read -p "Update Kubernetes manifests with these values? (Y/n) " UPDATE_K8S
if [[ ! "$UPDATE_K8S" =~ ^[Nn] ]]; then
    if [ -f "$SCRIPT_DIR/update-k8s-images.sh" ]; then
        "$SCRIPT_DIR/update-k8s-images.sh"
    else
        log_warn "update-k8s-images.sh not found. Run it manually after creation."
    fi
fi

echo ""
log_info "Setup complete!"
echo ""
echo "Next steps:"
echo "  1. Run 'make setup' to install dependencies"
echo "  2. Run 'make env-setup' to create backend/.env and frontend/.env"
echo "  3. Run 'make db-start && make db-init && make db-seed' to initialize database"
echo "  4. Run 'make dev' to start development servers"
echo "  5. Commit project.env and updated k8s manifests to git"
echo ""
