apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  labels:
    app: backend
    component: migration
spec:
  template:
    metadata:
      labels:
        app: backend
        component: migration
    spec:
      restartPolicy: OnFailure
      containers:
      - name: alembic
        image: quay.io/cfchase/patternfly-fastapi-backend:latest
        command:
        - /bin/sh
        - -c
        - |
          cd /app/backend
          uv run alembic upgrade head
        env:
        - name: POSTGRES_SERVER
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: database
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
